require('paq') {
  'savq/paq-nvim',
  'mahyarap/badwolf',
  'cormacrelf/vim-colors-github',
  'lifepillar/vim-solarized8',
  'nvim-lua/plenary.nvim',
  'nvim-telescope/telescope.nvim',
  'tpope/vim-fugitive',
  'williamboman/mason.nvim',
  'neovim/nvim-lspconfig',
  'airblade/vim-gitgutter',
  'windwp/nvim-autopairs',
  'mfussenegger/nvim-lint',
  'nvim-treesitter/nvim-treesitter',
  'nvim-treesitter/nvim-treesitter-context',
}
